//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnionPressOnSharp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=USER\\SQLEXPRESS;Initial Catalog=Souz_Pechati;Integrated Security=True" +
            "")]
        public string Souz_PechatiConnectionString {
            get {
                return ((string)(this["Souz_PechatiConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 100, 200")]
        public global::System.Drawing.Color ColorButSet {
            get {
                return ((global::System.Drawing.Color)(this["ColorButSet"]));
            }
            set {
                this["ColorButSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StyleIsSelect {
            get {
                return ((bool)(this["StyleIsSelect"]));
            }
            set {
                this["StyleIsSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColorPanelSet {
            get {
                return ((global::System.Drawing.Color)(this["ColorPanelSet"]));
            }
            set {
                this["ColorPanelSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gainsboro")]
        public global::System.Drawing.Color ColorFontBtnSet {
            get {
                return ((global::System.Drawing.Color)(this["ColorFontBtnSet"]));
            }
            set {
                this["ColorFontBtnSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SizeFontSet {
            get {
                return ((int)(this["SizeFontSet"]));
            }
            set {
                this["SizeFontSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorBorderSet {
            get {
                return ((global::System.Drawing.Color)(this["ColorBorderSet"]));
            }
            set {
                this["ColorBorderSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int RadiusWinBorder {
            get {
                return ((int)(this["RadiusWinBorder"]));
            }
            set {
                this["RadiusWinBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SizeWinBorder {
            get {
                return ((int)(this["SizeWinBorder"]));
            }
            set {
                this["SizeWinBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ColorFontLblSet {
            get {
                return ((global::System.Drawing.Color)(this["ColorFontLblSet"]));
            }
            set {
                this["ColorFontLblSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorTextBoxSet {
            get {
                return ((global::System.Drawing.Color)(this["ColorTextBoxSet"]));
            }
            set {
                this["ColorTextBoxSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsMoving {
            get {
                return ((bool)(this["IsMoving"]));
            }
            set {
                this["IsMoving"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StyleIsSelect2 {
            get {
                return ((bool)(this["StyleIsSelect2"]));
            }
            set {
                this["StyleIsSelect2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ColorTxtFocus {
            get {
                return ((global::System.Drawing.Color)(this["ColorTxtFocus"]));
            }
            set {
                this["ColorTxtFocus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CountBtnClick {
            get {
                return ((int)(this["CountBtnClick"]));
            }
            set {
                this["CountBtnClick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CountSearchClick {
            get {
                return ((int)(this["CountSearchClick"]));
            }
            set {
                this["CountSearchClick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppsTime {
            get {
                return ((string)(this["AppsTime"]));
            }
            set {
                this["AppsTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterWorkers {
            get {
                return ((int)(this["CounterWorkers"]));
            }
            set {
                this["CounterWorkers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterPress {
            get {
                return ((int)(this["CounterPress"]));
            }
            set {
                this["CounterPress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterTypePress {
            get {
                return ((int)(this["CounterTypePress"]));
            }
            set {
                this["CounterTypePress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterPeriodPress {
            get {
                return ((int)(this["CounterPeriodPress"]));
            }
            set {
                this["CounterPeriodPress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterGraphic {
            get {
                return ((int)(this["CounterGraphic"]));
            }
            set {
                this["CounterGraphic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterOptions {
            get {
                return ((int)(this["CounterOptions"]));
            }
            set {
                this["CounterOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterStatistics {
            get {
                return ((int)(this["CounterStatistics"]));
            }
            set {
                this["CounterStatistics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterExit {
            get {
                return ((int)(this["CounterExit"]));
            }
            set {
                this["CounterExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterConnect {
            get {
                return ((int)(this["CounterConnect"]));
            }
            set {
                this["CounterConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterLogoMP {
            get {
                return ((int)(this["CounterLogoMP"]));
            }
            set {
                this["CounterLogoMP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterDostavka {
            get {
                return ((int)(this["CounterDostavka"]));
            }
            set {
                this["CounterDostavka"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterColorText {
            get {
                return ((int)(this["CounterColorText"]));
            }
            set {
                this["CounterColorText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterColorBorder {
            get {
                return ((int)(this["CounterColorBorder"]));
            }
            set {
                this["CounterColorBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterBorderRadius {
            get {
                return ((int)(this["CounterBorderRadius"]));
            }
            set {
                this["CounterBorderRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterBorderSize {
            get {
                return ((int)(this["CounterBorderSize"]));
            }
            set {
                this["CounterBorderSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterStyleSet {
            get {
                return ((int)(this["CounterStyleSet"]));
            }
            set {
                this["CounterStyleSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterTextSize {
            get {
                return ((int)(this["CounterTextSize"]));
            }
            set {
                this["CounterTextSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterColorTextBtn {
            get {
                return ((int)(this["CounterColorTextBtn"]));
            }
            set {
                this["CounterColorTextBtn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterColorBtnSet {
            get {
                return ((int)(this["CounterColorBtnSet"]));
            }
            set {
                this["CounterColorBtnSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterColorTextBoxSet {
            get {
                return ((int)(this["CounterColorTextBoxSet"]));
            }
            set {
                this["CounterColorTextBoxSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterDefaultClick {
            get {
                return ((int)(this["CounterDefaultClick"]));
            }
            set {
                this["CounterDefaultClick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterDropClick {
            get {
                return ((int)(this["CounterDropClick"]));
            }
            set {
                this["CounterDropClick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterToggleBtnMoving {
            get {
                return ((int)(this["CounterToggleBtnMoving"]));
            }
            set {
                this["CounterToggleBtnMoving"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterDelete {
            get {
                return ((int)(this["CounterDelete"]));
            }
            set {
                this["CounterDelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterAdd {
            get {
                return ((int)(this["CounterAdd"]));
            }
            set {
                this["CounterAdd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterSave {
            get {
                return ((int)(this["CounterSave"]));
            }
            set {
                this["CounterSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterBack {
            get {
                return ((int)(this["CounterBack"]));
            }
            set {
                this["CounterBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterUpdate {
            get {
                return ((int)(this["CounterUpdate"]));
            }
            set {
                this["CounterUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterExport {
            get {
                return ((int)(this["CounterExport"]));
            }
            set {
                this["CounterExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterLoad {
            get {
                return ((int)(this["CounterLoad"]));
            }
            set {
                this["CounterLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounterEdit {
            get {
                return ((int)(this["CounterEdit"]));
            }
            set {
                this["CounterEdit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckRegistration {
            get {
                return ((bool)(this["CheckRegistration"]));
            }
            set {
                this["CheckRegistration"] = value;
            }
        }
    }
}
